env:
  browser: true
  node: true
  es6: true
  jquery: true
extends: 
    - 'eslint:recommended'
    - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  linebreak-style:
    - error
    - unix
  no-console: 0
  no-unused-vars: ["error", { "args": "none" }]
  react/prop-types: 0
