env:
  browser: true
  node: true
  es6: true
extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  linebreak-style:
    - error
    - unix
  no-console: 0
  no-unused-vars: ["error", { "vars": "all", "args": "after-used", "ignoreRestSiblings": false }]
  react/prop-types: 0
  no-debugger: 1
  react/jsx-equals-spacing: [2, "always"]
